# Diabetes Dataset

In [1]:
# Initial imports
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.svm import SVC
%matplotlib inline

# Needed for decision tree visualization
import pydotplus
from IPython.display import Image

## Loading and Preprocessing Data

In [2]:
# Loading data
df_diab = pd.read_csv("./Resources/diabetes.csv")
df_diab.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [3]:
df_clean = df_diab.copy()

In [4]:
df_clean[df_clean.columns[1:5]]==0

     Glucose  BloodPressure  SkinThickness  Insulin
0      False          False          False     True
1      False          False          False     True
2      False          False           True     True
3      False          False          False    False
4      False          False          False    False
..       ...            ...            ...      ...
763    False          False          False    False
764    False          False          False     True
765    False          False          False    False
766    False          False           True     True
767    False          False          False     True

[768 rows x 4 columns]

In [5]:
df_2 = df_clean[~(df_clean[df_clean.columns[1:5]]==0).any(axis=1)]

In [6]:
df_2

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
13,1,189,60,23,846,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
753,0,181,88,44,510,43.3,0.222,26,1
755,1,128,88,39,110,36.5,1.057,37,1
760,2,88,58,26,16,28.4,0.766,22,0
763,10,101,76,48,180,32.9,0.171,63,0
765,5,121,72,23,112,26.2,0.245,30,0

In [7]:
# Define features set

X = df_2.copy()
X.drop("Outcome",axis=1, inplace=True)
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
6,3,78,50,32,88,31.0,0.248,26
8,2,197,70,45,543,30.5,0.158,53
13,1,189,60,23,846,30.1,0.398,59

In [8]:
#check the shape
X.shape

(393, 8)

In [9]:
# Define target vector
y = df_2["Outcome"].ravel()
y[:5]

array([0, 1, 1, 1, 1], dtype=int64)

In [10]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [11]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [12]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [13]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# SVM MODEL

In [14]:
#Remove Outcome target from features data
y = df_2.Outcome.values
X = df_2.drop(columns="Outcome").values

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [16]:
# Support vector machine linear classifier
model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [17]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

Test Acc: 0.758

In [18]:
# Calculate the classification report
predictions = model.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.81      0.85      0.83        68
           1       0.63      0.55      0.59        31

    accuracy                           0.76        99
   macro avg       0.72      0.70      0.71        99
weighted avg       0.75      0.76      0.75        99